export const fromlabels = [
  {
    name: "name",
    label: "Name",
    required: true,
    message: "Please input your Name",
    visible: true,
    placeholder: "John Doe",
  },
  {
    name: "email",
    label: "Email",
    required: true,
    message: "Please input your Email",
    visible: true,
    placeholder: "example@example.com",
  },
  {
    name: "phone",
    label: "Phone",
    required: false,
    message: "Please input your Phone",
    visible: true,
    placeholder: "(123) 456-7890",
  },
  {
    name: "address",
    label: "Address",
    required: false,
    message: "Please input your Address",
    visible: true,
    placeholder: "123 Main St",
  },
  {
    name: "city",
    label: "City",
    required: false,
    message: "Please input your City",
    visible: true,
    placeholder: "New York",
  },
  {
    name: "country",
    label: "Country",
    required: false,
    message: "Please input your Country",
    visible: true,
    placeholder: "Kenya",
  },
  {
    name: "zipcode",
    label: "Zip Code",
    required: false,
    message: "Please input your Zip Code",
    visible: true,
    placeholder: "10001",
  },
  {
    name: "website",
    label: "Website",
    required: false,
    message: "Please input your Website",
    visible: true,
    placeholder: "https://www.example.com",
  },
];
export const tolabels = [
  {
    name: "name",
    label: "Name",
    required: true,
    message: "Please input your Name",
    visible: true,
    placeholder: "John Doe",
  },
  {
    name: "email",
    label: "Email",
    required: true,
    message: "Please input your Email",
    visible: true,
    placeholder: "example@example.com",
  },
  {
    name: "phone",
    label: "Phone",
    required: false,
    message: "Please input your Phone",
    visible: true,
    placeholder: "(123) 456-7890",
  },
  {
    name: "address",
    label: "Address",
    required: false,
    message: "Please input your Address",
    visible: true,
    placeholder: "123 Main St",
  },
  {
    name: "city",
    label: "City",
    required: false,
    message: "Please input your City",
    visible: true,
    placeholder: "New York",
  },
  {
    name: "country",
    label: "Country",
    required: false,
    message: "Please input your Country",
    visible: true,
    placeholder: "Kenya",
  },
  {
    name: "zipcode",
    label: "Zip Code",
    required: false,
    message: "Please input your Zip Code",
    visible: true,
    placeholder: "10001",
  },
  {
    name: "website",
    label: "Website",
    required: false,
    message: "Please input your Website",
    visible: true,
    placeholder: "https://www.example.com",
  },
];

export const customizelabels = [
  {
    name: "invoicetitle",
    label: "InvoiceTitle",
    required: false,
    message: "Please input your invoice Title",
    visible: true,
    placeholder: "Invoice",
  },
  {
    name: "estimatetitle",
    label: "EstimateTitle",
    required: false,
    message: "Please input your Estimate Title",
    visible: true,
    placeholder: "Estimate",
  },
];

export const customizeTextArea = [
  { name: "invoicenotes", label: "InvoiceNotes" },
  { name: "estimatenotes", label: "EstimateNotes" },
  { name: "emailmessage", label: "EmailMessage" },
];
